spring:
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        generate_statistics: 'false'
        search:
          default:
            directory_provider: filesystem
            indexBase: ./data/index/default
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'false'
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    username: admin
    url: jdbc:h2:./data/library;DB_CLOSE_ON_EXIT=TRUE
  h2:
    # Enabling H2 Console
    console:
      path: /h2-console
      enabled: 'true'
  sql:
    init:
      mode: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
  mvc:
    pathmatch:
      # https://stackoverflow.com/questions/70043841/swagger-2-issue-spring-boot
      matching-strategy: ant-path-matcher
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
server:
  port: '8080'
